#!/usr/bin/env python3
"""
Generate GitHub Actions milestone workflow with pre-calculated cron schedules.

Reads config/semesters.yaml, calculates the exact datetime each milestone
percentage is reached for each semester, and generates a workflow YAML
with cron entries for each milestone.

Usage:
    python scripts/generate_milestones.py              # Generate workflow
    python scripts/generate_milestones.py --preview     # Preview milestones only
"""

import argparse
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.calendar import load_semesters, load_milestones, TZ

WORKFLOW_PATH = Path(__file__).parent.parent / ".github" / "workflows" / "milestone_post.yml"


def calculate_milestone_times(
    config_path: Path | None = None,
) -> list[dict]:
    """
    Calculate the exact datetime for each milestone in each semester.

    Returns a list of dicts with keys: semester_name, milestone, datetime, cron.
    """
    semesters = load_semesters(config_path)
    milestones = load_milestones(config_path)
    now = datetime.now(tz=TZ)

    results = []
    for sem in semesters:
        # Skip past semesters
        if sem.progress_at(now) >= 100 and not sem.is_active(now):
            continue

        for m in milestones:
            if m == 0:
                continue

            dt = sem.milestone_datetime(m)

            # Skip milestones already passed
            if dt < now:
                continue

            # Convert to UTC for cron (GitHub Actions uses UTC)
            dt_utc = dt.astimezone(ZoneInfo("UTC"))

            # Cron: minute hour day month *
            cron = f"{dt_utc.minute} {dt_utc.hour} {dt_utc.day} {dt_utc.month} *"

            results.append(
                {
                    "semester_name": sem.display_name,
                    "milestone": m,
                    "datetime": dt,
                    "datetime_utc": dt_utc,
                    "cron": cron,
                }
            )

    results.sort(key=lambda r: r["datetime"])
    return results


def generate_workflow(milestone_times: list[dict]) -> str:
    """Generate the GitHub Actions workflow YAML content."""
    # Collect unique cron entries (GitHub allows max ~20 schedules)
    cron_entries = []
    for mt in milestone_times:
        cron_entries.append(f"    - cron: '{mt['cron']}'  # {mt['semester_name']} {mt['milestone']}%")

    # If too many, warn
    if len(cron_entries) > 20:
        print(f"WARNING: {len(cron_entries)} cron entries exceed GitHub's limit. "
              "Consider reducing milestones or semesters.", file=sys.stderr)

    cron_block = "\n".join(cron_entries)

    workflow = f"""# AUTO-GENERATED by scripts/generate_milestones.py
# Do not edit manually. Re-run the script after updating config/semesters.yaml.
#
# Milestone posts at pre-calculated times.

name: Milestone Twitter Post

on:
  schedule:
{cron_block}
  workflow_dispatch:
    inputs:
      force:
        description: 'Force milestone post regardless of timing'
        type: boolean
        default: false

jobs:
  post_milestone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Post milestone tweet
        env:
          API_KEY: ${{{{ secrets.API_KEY }}}}
          API_KEY_SECRET: ${{{{ secrets.API_KEY_SECRET }}}}
          ACCESS_TOKEN: ${{{{ secrets.ACCESS_TOKEN }}}}
          ACCESS_TOKEN_SECRET: ${{{{ secrets.ACCESS_TOKEN_SECRET }}}}
          BEARER_TOKEN: ${{{{ secrets.BEARER_TOKEN }}}}
        run: python main.py --milestone
"""
    return workflow


def main():
    parser = argparse.ArgumentParser(
        description="Generate milestone workflow from semester config"
    )
    parser.add_argument(
        "--preview",
        action="store_true",
        help="Preview milestone times without generating workflow.",
    )
    parser.add_argument(
        "--config",
        type=str,
        help="Path to semesters.yaml config file.",
    )
    args = parser.parse_args()

    config_path = Path(args.config) if args.config else None
    milestone_times = calculate_milestone_times(config_path)

    if not milestone_times:
        print("No upcoming milestones found.")
        sys.exit(0)

    print(f"Found {len(milestone_times)} upcoming milestone(s):\n")
    for mt in milestone_times:
        print(
            f"  {mt['semester_name']} | {mt['milestone']:>3}% | "
            f"{mt['datetime'].strftime('%Y-%m-%d %H:%M %Z')} | "
            f"cron: {mt['cron']}"
        )

    if args.preview:
        return

    workflow = generate_workflow(milestone_times)

    WORKFLOW_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(WORKFLOW_PATH, "w", encoding="utf-8") as f:
        f.write(workflow)

    print(f"\nWorkflow written to: {WORKFLOW_PATH}")
    print("Remember to commit and push this file for the schedule to take effect.")


if __name__ == "__main__":
    main()
